# -*- coding: utf-8 -*-
"""Municipios de Cundinamarca y Tolima (fuente: DANE vía marcovega/colombia-json)."""
import unicodedata

MUNICIPIOS = [
    'Agua de Dios',
    'Albán',
    'Alpujarra',
    'Alvarado',
    'Ambalema',
    'Anapoima',
    'Anolaima',
    'Anzoátegui',
    'Apulo',
    'Arbeláez',
    'Armero',
    'Ataco',
    'Beltrán',
    'Bituima',
    'Bogotá',
    'Bojacá',
    'Cabrera',
    'Cachipay',
    'Cajamarca',
    'Cajicá',
    'Caparrapí',
    'Carmen de Apicalá',
    'Carmen de Carupa',
    'Casabianca',
    'Chaguaní',
    'Chaparral',
    'Chipaque',
    'Choachí',
    'Chocontá',
    'Chía',
    'Coello',
    'Cogua',
    'Cota',
    'Coyaima',
    'Cucunubá',
    'Cunday',
    'Cáqueza',
    'Dolores',
    'El Colegio',
    'El Espinal',
    'El Peñón',
    'El Rosal',
    'Facatativá',
    'Falán',
    'Flandes',
    'Fosca',
    'Fresno',
    'Funza',
    'Fusagasugá',
    'Fómeque',
    'Fúquene',
    'Gachalá',
    'Gachancipá',
    'Gachetá',
    'Gama',
    'Girardot',
    'Granada',
    'Guachetá',
    'Guaduas',
    'Guamo',
    'Guasca',
    'Guataquí',
    'Guatavita',
    'Guayabal de Síquima',
    'Guayabetal',
    'Gutiérrez',
    'Herveo',
    'Honda',
    'Ibagué',
    'Icononzo',
    'Jerusalén',
    'Junín',
    'La Calera',
    'La Mesa',
    'La Palma',
    'La Peña',
    'La Vega',
    'Lenguazaque',
    'Lérida',
    'Líbano',
    'Machetá',
    'Madrid',
    'Manta',
    'Mariquita',
    'Medina',
    'Melgar',
    'Mosquera',
    'Murillo',
    'Nariño',
    'Natagaima',
    'Nemocón',
    'Nilo',
    'Nimaima',
    'Nocaima',
    'Ortega',
    'Pacho',
    'Paime',
    'Palocabildo',
    'Pandi',
    'Paratebueno',
    'Pasca',
    'Piedras',
    'Planadas',
    'Prado',
    'Puerto Salgar',
    'Pulí',
    'Purificación',
    'Quebradanegra',
    'Quetame',
    'Quipile',
    'Ricaurte',
    'Rioblanco',
    'Roncesvalles',
    'Rovira',
    'Saldaña',
    'San Antonio',
    'San Antonio del Tequendama',
    'San Bernardo',
    'San Cayetano',
    'San Francisco',
    'San Juan de Rioseco',
    'San Luis',
    'Santa Isabel',
    'Sasaima',
    'Sesquilé',
    'Sibaté',
    'Silvania',
    'Simijaca',
    'Soacha',
    'Sopó',
    'Subachoque',
    'Suesca',
    'Supatá',
    'Susa',
    'Sutatausa',
    'Suárez',
    'Tabio',
    'Tausa',
    'Tena',
    'Tenjo',
    'Tibacuy',
    'Tibirita',
    'Tocaima',
    'Tocancipá',
    'Topaipí',
    'Ubalá',
    'Ubaque',
    'Ubaté',
    'Une',
    'Valle de San Juan',
    'Venadillo',
    'Venecia',
    'Vergara',
    'Vianí',
    'Villagómez',
    'Villahermosa',
    'Villapinzón',
    'Villarrica',
    'Villeta',
    'Viotá',
    'Yacopí',
    'Zipacón',
    'Zipaquirá',
    'Útica',
]

def _normalizar(texto):
    """minúsculas y sin tildes, para comparar sin importar acentos/mayúsculas."""
    texto = unicodedata.normalize("NFD", texto.lower())
    return "".join(c for c in texto if unicodedata.category(c) != "Mn").strip()


def buscar(prefijo, limite=30):
    """Devuelve municipios que CONTIENEN el texto, sin importar tildes/mayúsculas."""
    p = _normalizar(prefijo)
    if not p:
        return []
    coincidencias = [m for m in MUNICIPIOS if p in _normalizar(m)]
    return coincidencias[:limite]


def es_valido(nombre):
    """True si el nombre coincide exactamente (normalizado) con un municipio real."""
    n = _normalizar(nombre)
    return any(_normalizar(m) == n for m in MUNICIPIOS)


def canonico(nombre):
    """Devuelve la grafía oficial del municipio (o None si no existe)."""
    n = _normalizar(nombre)
    for m in MUNICIPIOS:
        if _normalizar(m) == n:
            return m
    return None